# Generated by Django 3.0.7 on 2020-06-29 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20200629_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
